# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the Euclidean Norm of a Vector
#'
#' C++ implementation of the Euclidean norm calculations for a vector. This
#' improves computation time, but may introduce numerical instability.
#'
#' @param x A numeric vector of values.
#'
#' @return A numeric value.
#' @export
#'
#' @examples
#' x <- 1:10
#' norm_euclidean(x)
norm_euclidean <- function(x) {
    .Call(`_pme_norm_euclidean`, x)
}

norm_euclidean2 <- function(x) {
    .Call(`_pme_norm_euclidean2`, x)
}

