# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the Euclidean Norm of a Vector
#'
#' C++ implementation of the Euclidean norm calculations for a vector. This
#' is meant for internal use for the Rcpp implementation.
#'
#' @param x A numeric vector of values.
#'
#' @return A numeric value.
#' @export
#'
#' @examples
#' x <- 1:10
#' norm_euclidean(x)
norm_euclidean <- function(x) {
    .Call(`_pme_norm_euclidean`, x)
}

#' Compute the Euclidean Distance between Vectors
#'
#' C++ implementation of Euclidean distance calculations for use in
#' internal Rcpp functions.
#'
#' @param x, y Numeric vectors of values.
#'
#' @return A numeric value.
#' @export
#'
#' @examples
#' x <- 1:10
#' y <- 91:100
#' dist_euclidean(x, y)
dist_euclidean <- function(x, y) {
    .Call(`_pme_dist_euclidean`, x, y)
}

