# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' RcppArmadillo Hello World
#'
#' This is a simple example of creating two matrices and returning
#' the result of an operation on them.
#'
#' @export
#' @examples
#' rcpparma_hello_world
rcpparma_hello_world <- function() {
    .Call(`_pme_rcpparma_hello_world`)
}

norm_euclidean <- function(x) {
    .Call(`_pme_norm_euclidean`, x)
}

